//header automatically generated by autoHead
#pragma once
#include <stdio.h>
#define BLUE "\033[38;2;35;35;255m" 
#define RED "\033[38;2;255;0;0m" 
#define YELLOW "\033[38;2;255;255;0m" 
#define ORANGE "\033[38;2;255;128;0m"
#define PURPLE "\033[38;2;150;25;255m"
#define GREEN "\033[38;2;0;255;0m"
#define GRAY "\033[38;2;176;196;222m"
#define LIGHT_BLUE "\033[38;2;135;206;235m" 
void gaymer_print(char* str);
